### ISSUE TITLE
Colab ran out of memory when saving the model

### ISSUE THREAD

**Issue by nolanaatama** [geocine/sd-easy-mode#1]
Hello, first of all thank you for your work.
This colab is really helpful for us the complete beginner in dreambooth.

Few days ago, I use this colab and it works fine.
I even make a video tutorial about it on YouTube and upload it today:
https://youtu.be/HVOvL2CyBT0

But today it seems the colab having run out of memory issue when trying to save the model to Google Drive.
![Untitled](https://user-images.githubusercontent.com/119261289/213913013-93fdc90e-b5af-4f8a-8cec-b463152192ac.jpg)

I try using the previous version when I create the video and it also stop working on the 'Upload' section regarding the 'SDD_TOKEN', maybe it's because the recent change in the script?

Some our friends in my channel really interested to use your colab and we hope we can use it again cleanly like before.
Once again, thank you for your great work.
Cheers.

**Comment by geocine** [comment]
I don't know what's up with Colab right now. But I did update the code hours ago. so that your changes won't be deleted if it crashes like this. You can just click the button next to save then it will proceed.

**Comment by geocine** [comment]
What I mean is right now it will really crash the first time you click on Save. Just wait for it to crash, once it reconnects just run save again and it should be successful the second time around. 

This happens if you generate images, for some reason the memory does not clear after generating images.

**Comment by geocine** [comment]
Btw, I can see your colab is outdated from the update I did last night. You can refresh and try again. You should see these thing below which indicates that it is updated.

![image](https://user-images.githubusercontent.com/507464/213913951-b12325b0-1757-4dad-b68e-27c55a232e83.png)

**Comment by geocine** [comment]
@nolanaatama can you add me on discord lets talk `crevace#2696`

**Comment by geocine** [comment]
I just updated just now. I forgot to add `import json` on my latest fix. I read this comment on the youtube

![image](https://user-images.githubusercontent.com/507464/213914161-71880c6c-b3fc-4cd5-8b45-3c18be84ee0f.png)

**Comment by nolanaatama** [comment]
all is fine now. thank you for your quick response!
I already sent you a friend request on discord.
once again, thank you for your work. cheers

**Comment by geocine** [comment]
> all is fine now. thank you for your quick response! I already sent you a friend request on discord. once again, thank you for your work. cheers

you're welcome sent you a message on discord. feel free to contact me
