### ISSUE TITLE
new error 

### ISSUE THREAD

**Issue by WalidAliAlfaid** [geocine/sd-easy-mode#11]
│ /content/train_dreambooth.py:869 in <module>                                 │
│                                                                              │
│   866                                                                        │
│   867 if __name__ == "__main__":                                             │
│   868 │   args = parse_args()                                                │
│ ❱ 869 │   main(args)                                                         │
│   870                                                                        │
│                                                                              │
│ /content/train_dreambooth.py:553 in main                                     │
│                                                                              │
│   550 │   │   text_encoder.requires_grad_(False)                             │
│   551 │                                                                      │
│   552 │   if is_xformers_available():                                        │
│ ❱ 553 │   │   vae.enable_xformers_memory_efficient_attention()               │
│   554 │   │   unet.enable_xformers_memory_efficient_attention()              │
│   555 │   else:                                                              │
│   556 │   │   logger.warning("xformers is not available. Make sure it is ins │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/modeling_utils.py:25 │
│ 1 in enable_xformers_memory_efficient_attention                              │
│                                                                              │
│   248 │   │   >>> model.enable_xformers_memory_efficient_attention(attention │
│   249 │   │   ```                                                            │
│   250 │   │   """                                                            │
│ ❱ 251 │   │   self.set_use_memory_efficient_attention_xformers(True, attenti │
│   252 │                                                                      │
│   253 │   def disable_xformers_memory_efficient_attention(self):             │
│   254 │   │   r"""                                                           │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/modeling_utils.py:21 │
│ 9 in set_use_memory_efficient_attention_xformers                             │
│                                                                              │
│   216 │   │                                                                  │
│   217 │   │   for module in self.children():                                 │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                    │
│ ❱ 219 │   │   │   │   fn_recursive_set_mem_eff(module)                       │
│   220 │                                                                      │
│   221 │   def enable_xformers_memory_efficient_attention(self, attention_op: │
│   222 │   │   r"""                                                           │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/modeling_utils.py:21 │
│ 5 in fn_recursive_set_mem_eff                                                │
│                                                                              │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(val │
│   213 │   │   │                                                              │
│   214 │   │   │   for child in module.children():                            │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                        │
│   216 │   │                                                                  │
│   217 │   │   for module in self.children():                                 │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                    │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/modeling_utils.py:21 │
│ 5 in fn_recursive_set_mem_eff                                                │
│                                                                              │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(val │
│   213 │   │   │                                                              │
│   214 │   │   │   for child in module.children():                            │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                        │
│   216 │   │                                                                  │
│   217 │   │   for module in self.children():                                 │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                    │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/modeling_utils.py:21 │
│ 5 in fn_recursive_set_mem_eff                                                │
│                                                                              │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(val │
│   213 │   │   │                                                              │
│   214 │   │   │   for child in module.children():                            │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                        │
│   216 │   │                                                                  │
│   217 │   │   for module in self.children():                                 │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                    │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/modeling_utils.py:21 │
│ 2 in fn_recursive_set_mem_eff                                                │
│                                                                              │
│   209 │   │   # gets the message                                             │
│   210 │   │   def fn_recursive_set_mem_eff(module: torch.nn.Module):         │
│   211 │   │   │   if hasattr(module, "set_use_memory_efficient_attention_xfo │
│ ❱ 212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(val │
│   213 │   │   │                                                              │
│   214 │   │   │   for child in module.children():                            │
│   215 │   │   │   │   fn_recursive_set_mem_eff(child)                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py:117 in  │
│ set_use_memory_efficient_attention_xformers                                  │
│                                                                              │
│   114 │   │   │   │   │   │   torch.randn((1, 2, 40), device="cuda"),        │
│   115 │   │   │   │   │   )                                                  │
│   116 │   │   │   │   except Exception as e:                                 │
│ ❱ 117 │   │   │   │   │   raise e                                            │
│   118 │   │   self._use_memory_efficient_attention_xformers = use_memory_eff │
│   119 │   │   self._attention_op = attention_op                              │
│   120                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py:111 in  │
│ set_use_memory_efficient_attention_xformers                                  │
│                                                                              │
│   108 │   │   │   else:                                                      │
│   109 │   │   │   │   try:                                                   │
│   110 │   │   │   │   │   # Make sure we can run the memory efficient attent │
│ ❱ 111 │   │   │   │   │   _ = xformers.ops.memory_efficient_attention(       │
│   112 │   │   │   │   │   │   torch.randn((1, 2, 40), device="cuda"),        │
│   113 │   │   │   │   │   │   torch.randn((1, 2, 40), device="cuda"),        │
│   114 │   │   │   │   │   │   torch.randn((1, 2, 40), device="cuda"),        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/xformers/ops/fmha/__init__.py:196 in  │
│ memory_efficient_attention                                                   │
│                                                                              │
│   193 │   │   and options.                                                   │
│   194 │   :return: multi-head attention Tensor with shape ``[B, Mq, H, Kv]`` │
│   195 │   """                                                                │
│ ❱ 196 │   return _memory_efficient_attention(                                │
│   197 │   │   Inputs(                                                        │
│   198 │   │   │   query=query, key=key, value=value, p=p, attn_bias=attn_bia │
│   199 │   │   ),                                                             │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/xformers/ops/fmha/__init__.py:294 in  │
│ _memory_efficient_attention                                                  │
│                                                                              │
│   291 ) -> torch.Tensor:                                                     │
│   292 │   # fast-path that doesn't require computing the logsumexp for backw │
│   293 │   if all(x.requires_grad is False for x in [inp.query, inp.key, inp. │
│ ❱ 294 │   │   return _memory_efficient_attention_forward(                    │
│   295 │   │   │   inp, op=op[0] if op is not None else None                  │
│   296 │   │   )                                                              │
│   297                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/xformers/ops/fmha/__init__.py:310 in  │
│ _memory_efficient_attention_forward                                          │
│                                                                              │
│   307 │   inp.validate_inputs()                                              │
│   308 │   output_shape = inp.normalize_bmhk()                                │
│   309 │   if op is None:                                                     │
│ ❱ 310 │   │   op = _dispatch_fw(inp)                                         │
│   311 │   else:                                                              │
│   312 │   │   _ensure_op_supports_or_raise(ValueError, "memory_efficient_att │
│   313                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/xformers/ops/fmha/dispatch.py:98 in   │
│ _dispatch_fw                                                                 │
│                                                                              │
│    95 │   if _is_triton_fwd_fastest(inp):                                    │
│    96 │   │   priority_list_ops.remove(triton.FwOp)                          │
│    97 │   │   priority_list_ops.insert(0, triton.FwOp)                       │
│ ❱  98 │   return _run_priority_list(                                         │
│    99 │   │   "memory_efficient_attention_forward", priority_list_ops, inp   │
│   100 │   )                                                                  │
│   101                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/xformers/ops/fmha/dispatch.py:73 in   │
│ _run_priority_list                                                           │
│                                                                              │
│    70 {textwrap.indent(_format_inputs_description(inp), '     ')}"""         │
│    71 │   for op, not_supported in zip(priority_list, not_supported_reasons) │
│    72 │   │   msg += "\n" + _format_not_supported_reasons(op, not_supported) │
│ ❱  73 │   raise NotImplementedError(msg)                                     │
│    74                                                                        │
│    75                                                                        │
│    76 def _dispatch_fw(inp: Inputs) -> Type[AttentionFwOpBase]:              │
╰──────────────────────────────────────────────────────────────────────────────╯
NotImplementedError: No operator found for `memory_efficient_attention_forward` 
with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    requires A100 GPU
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/bin/accelerate:8 in <module>                                      │
│                                                                              │
│   5 from accelerate.commands.accelerate_cli import main                      │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py │
│ :45 in main                                                                  │
│                                                                              │
│   42 │   │   exit(1)                                                         │
│   43 │                                                                       │
│   44 │   # Run                                                               │
│ ❱ 45 │   args.func(args)                                                     │
│   46                                                                         │
│   47                                                                         │
│   48 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py:923 in  │
│ launch_command                                                               │
│                                                                              │
│   920 │   elif defaults is not None and defaults.compute_environment == Comp │
│   921 │   │   sagemaker_launcher(defaults, args)                             │
│   922 │   else:                                                              │
│ ❱ 923 │   │   simple_launcher(args)                                          │
│   924                                                                        │
│   925                                                                        │
│   926 def main():                                                            │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py:579 in  │
│ simple_launcher                                                              │
│                                                                              │
│   576 │   process.wait()                                                     │
│   577 │   if process.returncode != 0:                                        │
│   578 │   │   if not args.quiet:                                             │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.ret │
│   580 │   │   else:                                                          │
│   581 │   │   │   sys.exit(1)                                                │
│   582

**Comment by Emrex3507** [comment]
yes. I've been getting the same error since last night

**Comment by geocine** [comment]
Thanks for reporting , I haven't tested this for a while as been busy with other things. I will check changes on Shiv's repo , looks like something updated on xformers

**Comment by geocine** [comment]
Thank you for waiting this is fixed now

**Comment by Emrex3507** [comment]
thank youuu
