### ISSUE TITLE
Some 1.5 models don't work?

### ISSUE THREAD

**Issue by WalidAliAlfaid** [geocine/sd-easy-mode#12]
i followed Training Custom Models tutorial it works well on the well known models like dreamsharper but for the less known like iCoMix it doesn't 

Traceback (most recent call last) ──────────────────────╮
│ /content/train_dreambooth.py:869 in <module>                                 │
│                                                                              │
│   866                                                                        │
│   867 if __name__ == "__main__":                                             │
│   868 │   args = parse_args()                                                │
│ ❱ 869 │   main(args)                                                         │
│   870                                                                        │
│                                                                              │
│ /content/train_dreambooth.py:524 in main                                     │
│                                                                              │
│   521 │   │   │   revision=args.revision,                                    │
│   522 │   │   )                                                              │
│   523 │   elif args.pretrained_model_name_or_path:                           │
│ ❱ 524 │   │   tokenizer = CLIPTokenizer.from_pretrained(                     │
│   525 │   │   │   args.pretrained_model_name_or_path,                        │
│   526 │   │   │   subfolder="tokenizer",                                     │
│   527 │   │   │   revision=args.revision,                                    │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base. │
│ py:1788 in from_pretrained                                                   │
│                                                                              │
│   1785 │   │   │   )                                                         │
│   1786 │   │                                                                 │
│   1787 │   │   if all(full_file_name is None for full_file_name in resolved_ │
│ ❱ 1788 │   │   │   raise EnvironmentError(                                   │
│   1789 │   │   │   │   f"Can't load tokenizer for '{pretrained_model_name_or │
│   1790 │   │   │   │   "'https://huggingface.co/models', make sure you don't │
│   1791 │   │   │   │   f"Otherwise, make sure '{pretrained_model_name_or_pat │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: Can't load tokenizer for 'coreml/coreml-iCoMix'. If you were trying to 
load it from 'https://huggingface.co/models', make sure you don't have a local 
directory with the same name. Otherwise, make sure 'coreml/coreml-iCoMix' is the
correct path to a directory containing all relevant files for a CLIPTokenizer 
tokenizer.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/bin/accelerate:8 in <module>                                      │
│                                                                              │
│   5 from accelerate.commands.accelerate_cli import main                      │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py │
│ :45 in main                                                                  │
│                                                                              │
│   42 │   │   exit(1)                                                         │
│   43 │                                                                       │
│   44 │   # Run                                                               │
│ ❱ 45 │   args.func(args)                                                     │
│   46                                                                         │
│   47                                                                         │
│   48 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py:923 in  │
│ launch_command                                                               │
│                                                                              │
│   920 │   elif defaults is not None and defaults.compute_environment == Comp │
│   921 │   │   sagemaker_launcher(defaults, args)                             │
│   922 │   else:                                                              │
│ ❱ 923 │   │   simple_launcher(args)                                          │
│   924                                                                        │
│   925                                                                        │
│   926 def main():                                                            │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py:579 in  │
│ simple_launcher                                                              │
│                                                                              │
│   576 │   process.wait()                                                     │
│   577 │   if process.returncode != 0:                                        │
│   578 │   │   if not args.quiet:                                             │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.ret │
│   580 │   │   else:                                                          │
│   581 │   │   │   sys.exit(1)                                                │
│   582

**Comment by geocine** [comment]
Can you post the link of the hugging face model

**Comment by WalidAliAlfaid** [comment]
yeah sure https://huggingface.co/coreml/coreml-iCoMix 
but i was hoping you fix that with all other unknown 1.5 models, i'm not exaggerating i tried all the trainning techniques and yours was always best!

**Comment by geocine** [comment]
The model you linked in not a diffusers model , its a coreml model that work only on Apple Silicon Devices. Its format is also in zip

![image](https://user-images.githubusercontent.com/507464/231559749-e291510b-62da-43b6-8654-1a1684f69558.png)

![image](https://user-images.githubusercontent.com/507464/231559847-0ca826c3-9e6f-4342-8f97-a1a21c9b119f.png)

All diffuser format models should work with this repository. If its not a diffuser model it will not work.

**Comment by WalidAliAlfaid** [comment]
can you add model converter just like this one https://colab.research.google.com/github/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb?authuser=2#scrollTo=I11LhntsJqeX

**Comment by geocine** [comment]
The converter on that link only supports `ckpt` and `safetensors` to `diffusers` format . It doesn't support `coreml` . I suggest to convert the models that you like to `diffusers` format and host it on HuggingFace then you can use it on this repo. 

Unfortunately adding features that can be done before (ex. conversion) / after (ex. uploading) processing , potentially introduces complexity which makes this project hard to maintain. This approach helps simplify the process and help ensure the script remains maintainable over time.
