### ISSUE TITLE
hello i appreciate you. please develop many models with dreambooth. very useful for us amd gpu owners

### ISSUE THREAD

**Issue by Emrex3507** [geocine/sd-easy-mode#13]
hello i appreciate you. please develop many models with dreambooth. very useful for us amd gpu owners

**Comment by geocine** [comment]
Hi thank you for the feedback. You can use any model as long as you can convert it to diffusers. You can use https://huggingface.co/spaces/diffusers/sd-to-diffusers to convert `ckpt` , `safetensors` to `diffusers` . You need to host it on huggingface then follow this tutorial how to use custom models https://github.com/geocine/sd-easy-mode#training-custom-models
