### ISSUE TITLE
Couldn't Upload Photos Above 60kb

### ISSUE THREAD

**Issue by T1NT1NHK** [geocine/sd-easy-mode#14]
First, Upload directly to [/data/training_images] is not working, also couldn't upload photos above 60kb per image which mean 512x512 was too big to upload, it shown below messages :

77020 bytes, last modified: n/a - 0% done
 ---------------------------------------------------------------------------
MessageError                              Traceback (most recent call last)
[<ipython-input-4-760b15bc3a53>](https://q68mymydb4m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230414-060104-RC00_524256009#) in <cell line: 19>()
     21     prompt = prompt.format(SDD_TOKEN=SDD_TOKEN, SDD_CLASS="")
     22     print(f"Uploading instance images for `{prompt}`")
---> 23     uploaded = files.upload()
     24     if not uploaded:
     25       print_message("error","Please run the Upload step again and select the images you want to use")

3 frames
[/usr/local/lib/python3.9/dist-packages/google/colab/files.py](https://q68mymydb4m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230414-060104-RC00_524256009#) in upload()
     67   """
     68 
---> 69   uploaded_files = _upload_files(multiple=True)
     70   # Mapping from original filename to filename as saved locally.
     71   local_filenames = dict()

[/usr/local/lib/python3.9/dist-packages/google/colab/files.py](https://q68mymydb4m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230414-060104-RC00_524256009#) in _upload_files(multiple)
    159 
    160   while result['action'] != 'complete':
--> 161     result = _output.eval_js(
    162         'google.colab._files._uploadFilesContinue("{output_id}")'.format(
    163             output_id=output_id

[/usr/local/lib/python3.9/dist-packages/google/colab/output/_js.py](https://q68mymydb4m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230414-060104-RC00_524256009#) in eval_js(script, ignore_result, timeout_sec)
     38   if ignore_result:
     39     return
---> 40   return _message.read_reply_from_input(request_id, timeout_sec)
     41 
     42 

[/usr/local/lib/python3.9/dist-packages/google/colab/_message.py](https://q68mymydb4m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230414-060104-RC00_524256009#) in read_reply_from_input(message_id, timeout_sec)
    101     ):
    102       if 'error' in reply:
--> 103         raise MessageError(reply['error'])
    104       return reply.get('data', None)
    105 

MessageError: RangeError: Maximum call stack size exceeded.

**Comment by geocine** [comment]
Direct upload feature is Google Colab feature, it has nothing to do with my script. 60 mb will take some time to upload because its too big. I suggest you compress your images using https://www.birme.net/ or similar tools. My 512x512 images are usually less than 1mb. 

This is how I upload using 9MB
![2017-08-27-231](https://user-images.githubusercontent.com/507464/232827732-58a2c698-d77d-4813-8a7b-4860c1ceff49.jpg)
Also below you will see a 512x512 image which is less than 2mb
![jisoo (15)](https://user-images.githubusercontent.com/507464/232828052-3d8aeb3a-2da8-40ac-85d9-0e6a3cf809d1.png)

**Comment by T1NT1NHK** [comment]
I can't upload 60kb above photo, not 60mb

**Comment by T1NT1NHK** [comment]
1mb = 1000kb
I can only upload 60kb in jpeg photos 🙏

**Comment by geocine** [comment]
You can resize your photo

**Comment by geocine** [comment]
Check my video I upload 9mb = 9000kb

https://user-images.githubusercontent.com/507464/232828451-18eebef6-b8d8-46ec-80df-e08aea0d5fbc.mp4

**Comment by T1NT1NHK** [comment]
thanks for your help
