### ISSUE TITLE
new error happens in Setup cell

### ISSUE THREAD

**Issue by WalidAliAlfaid** [geocine/sd-easy-mode#15]
nstalling: 88%
safetensors is already installed
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-4-032fe409c658>](https://localhost:8080/#) in <cell line: 77>()
     76 pb = ProgressBar(len(packages), "Installing")
     77 for package in packages:
---> 78     label = install_package(package, DIFFUSERS_URL, XFORMERS_URL, "exp", False)
     79     pb.update(label)
     80 print("\033[92mInstallation complete\033[0m")

1 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524         retcode = process.poll()
    525         if check and retcode:
--> 526             raise CalledProcessError(retcode, process.args,
    527                                      output=stdout, stderr=stderr)
    528     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['pip', 'install', 'https://github.com/geocine/dreamstall-binaries/releases/download/c117-p39-t1311-linux/xformers-0.0.18.dev500-cp39-cp39-manylinux2014_x86_64.whl']' returned non-zero exit status 1.

**Comment by geocine** [comment]
Fixed
