### ISSUE TITLE
PyTorch and torchvision Runtime Error - Different CUDA Versions Detected

### ISSUE THREAD

**Issue by luisstuto** [geocine/sd-easy-mode#17]
This doesnt work anymore, it appears this bug:

RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions

what to do?

**Comment by pilis38** [comment]
I found this solution on a different Github Discussion. Execute the following Code before doing any of the other steps and it should work fine (at least for me it fixed the problem):

%pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchtext==0.14.1 torchaudio==0.13.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu117

**Comment by geocine** [comment]
I'll get back to this on the weekend. The pytorch updates of Google Colab is always breaking things 

related #18
