### ISSUE TITLE
it would be really helpful if you add this at the end of the notebook

### ISSUE THREAD

**Issue by WalidAliAlfaid** [geocine/sd-easy-mode#19]
i found this converter code but i don't know how to use it. it convert models to Lora or LyCORIS

this is the script: python extract_locon.py --safetensors --device=cuda --mode="fixed" --linear_dim=64 --conv_dim=32 C:/Development/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV20_v20.ckpt F:/Development/StableDiffusion/SDModels/Models/2023-04-17/model_morgan_v1_realistic2_3000.ckpt C:/Development/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/locon/locon_morgan_v1_from_v1_64_32.safetensors

this is the link: https://rentry.co/lycoris-and-lora-from-dreambooth

**Comment by geocine** [comment]
I appreciate you directing me to that reference. Currently, I'm primarily concentrating on Dreambooth. I took a brief look at the link you shared, but it appears that the script converter isn't included. If you're keen on this feature, you're welcome to fork my project.
