### ISSUE TITLE
I get this error when i run the training step, tried it with multiple accounts even created a new once, change the images I still get the same thing!

### ISSUE THREAD

**Issue by WalidAliAlfaid** [geocine/sd-easy-mode#2]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 14.76 GiB total capacity; 10.17 GiB already allocated; 1.78 GiB free; 11.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/stable_diffusion_models/lyomarly', '--revision=fp16', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--sample_batch_size=4', '--max_train_steps=2889', '--save_interval=10000', '--save_min_steps=0', '--save_sample_prompt=photo of lyomarly man', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.

**Comment by geocine** [comment]
May I know how many images you used, I will try to reproduce issue later.

**Comment by WalidAliAlfaid** [comment]
i always use between 25 to 40 images but i don't think this is the issue because i tried retrain images i already trained to see what happens and i got the same error

**Comment by geocine** [comment]
@WalidAliAlfaid I am looking into it. I am running some trial now, if this succeed I will push my changes to main then you can test. I will let you know.

**Comment by geocine** [comment]
Its fixed now @WalidAliAlfaid

**Comment by WalidAliAlfaid** [comment]
YES!!! Thank you very much! Just one thing if it's possible how can I change the model?

**Comment by geocine** [comment]
I created a short video @WalidAliAlfaid . These are the steps, I cannot guarantee quality of the output as I have not been training on top of custom models.

https://user-images.githubusercontent.com/507464/216762480-b77f74bd-5bea-45e0-b4d2-2043166a1b67.mp4

**Comment by WalidAliAlfaid** [comment]
Thanks you again ❤️❤️
